---
title: "homework_3"
author: "Rashedul Islam"
date: "3/15/2023"
output: html_document
---
```{r}
#chooseCRANmirror()
local({r <- getOption("repos")
       r["CRAN"] <- "http://cran.r-project.org" 
       options(repos=r)
})
install.packages("stringr")
```


```{r}

install.packages ("flextable")
install.packages("gtsummary")
install.packages ("flextable")
install.packages("moments")
install.packages ("tidyverse")
install.packages ("gridExtra")
install.packages("ggExtra")
install.packages("ggMarginal")
install.packages("Hmisc")
install.packages("GGally")
install.packages("plyr")

```


```{r}
library(tidyverse)
library(readr)
library(gtsummary)
library(readr)
library(magrittr)
library(ggplot2)
library(gridExtra)
library(ggExtra)
library(Hmisc)
library(readr)
library(plyr)
library(flextable)
```

```{r}
df<-read_csv("bd_arsenic_data.csv")
df.gh<-read_csv("bd_green_house.csv")
```

```{r}
#Task1
str(df)
str(df.gh)
```
```{r}
#Task2
sum(is.na(df))
sum(is.na(df.gh))
```

```{r}
#Task3
summary_stat <- df %>% 
  dplyr::select(GAs, WAs, SAs, SPAs, SAoAs, SAoFe) %>%
  dplyr::summarise_all(list(Min = ~round(min(.), 2), 
                      Q25 = ~round(quantile(., 0.25), 2), 
                      Median = ~round(median(.), 2), 
                      Q75 = ~round(quantile(., 0.75), 2), 
                      Max = ~round(max(.), 2),
                      Mean = ~round(mean(.), 2), 
                      SD = ~round(sd(.), 3))) %>% 
  tidyr::pivot_longer(everything(), 
                      names_sep = "_", 
                      names_to = c("variable", ".value"))

library(flextable)
flextable::flextable(summary_stat, theme = "theme_booktabs") 

```

```{r}
#Task4
df %>% dplyr::select(Land_type,GAs, WAs, SAs, SPAs, SAoAs, SAoFe) %>%
  gtsummary::tbl_summary(by = Land_type, 
                          statistic = list(
                          all_continuous() ~ "{mean} ({sd})",
                          all_categorical() ~ "{n} / {N} ({p}%)"
                          ),
                          missing_text = "Missing-values") %>%
                          add_p()

```
```{r}
#Task5
ggplot(df, aes(SOC)) +
  geom_histogram()+
  xlab("SOC (mg/g)") + 
  ylab("Frequency")+
  ggtitle("Histogram of Soil SOC")
```
```{r}
#Task6
shapiro.test(df$SOC)
moments::skewness(df$SOC)
moments::kurtosis(df$SOC)
```

```{r}
#Task7
bd_green_house <- read_csv("bd_green_house.csv")
p <- ggplot(bd_green_house, aes(x = SW, y = GAs)) +
  geom_point(size = 2) +
  ggtitle("STAs vs GAs") +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(colour = "gray"),
    axis.title.x = element_text(size = 14), 
    axis.text.y = element_text(size = 12, vjust = 0.5, hjust = 0.5),
    axis.text.x = element_text(size = 12)
  ) +
  xlab("STAs") +
  ylab("GAs")

p_hist <- ggMarginal(p, type="histogram", size=10)

 p1<-ggplot(bd_green_house, aes(x = STAs, y = GAs)) +
  geom_point(size = 2) +
  ggtitle("STAs vs GAs") +
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(colour = "gray"),
    axis.title.x = element_text(size = 14), 
    axis.text.y = element_text(size = 12, vjust = 0.5, hjust = 0.5),
    axis.text.x = element_text(size = 12)
  ) +
  xlab("STAs") +
  ylab("GAs")

p1_hist <- ggMarginal(p1, type="histogram", size=10)

grid.arrange(p_hist, p1_hist,ncol=2)
```
```{r}
#Task8


df %>%
  arrange(desc(SOC)) %>%
  mutate(SOC = factor(SOC)) %>%
  ggplot(aes(x=SAND, y=SOC, size = 5, colour="gray")) +
    geom_point(alpha=0.5) +
    scale_size(range = c(.2, 4), name="MAT")+
     guides(color = guide_legend(title = "NLCD"))+
  ggtitle("Bubble Plot of Sand vs SOC") +
   theme(
    plot.title = element_text(hjust = 0.5),
    axis.line = element_line(colour = "gray"),
    axis.title.x = element_text(size = 14), 
    axis.text.y=element_text(size=12,vjust = 0.5, hjust=0.5),
    axis.text.x = element_text(size=12))+
  guides(color = guide_legend(title = "NLCD")) + 
  xlab("SAND") + 
  ylab("SOC") 
```


```{r}
#Task9

# create a data frame for correlation analysis
df.cor<-df %>% dplyr::select(GAs, StAs, WAs, SAs, SPAs, SAoAs,SAoFe) 
# correlation matrix
cor.mat<-Hmisc::rcorr(as.matrix(df.cor, type="pearson"))
cor.mat
```
```{r}
#Task10
GGally::ggpairs(df.cor)
```
```{r}
#Task11
SE <- function(x){
  sd(x)/sqrt(length(x))
}

# Get summary statistics
summarise_soc<-ddply(bd_green_house,~GAs, summarise, 
                Mean= round(mean(GAs), 3),
                Median=round (median(GAs), 3),
                Min= round (min(GAs),3), 
                Max= round (max(GAs),3), 
                SD= round(sd(GAs), 3), 
                SE= round (SE(GAs), 3))
# Load library

# Create a table
flextable::flextable(summarise_soc, theme_fun = theme_booktabs)
```


```{r}
ggplot(summarise_soc, aes(x=GAs, y=Mean)) + 
  geom_bar(stat="identity", position=position_dodge(),width=0.5, fill="gray") +
  geom_errorbar(aes(ymin=Mean-SE, ymax=Mean+SE), width=.2,
   position=position_dodge(.9))+
  # add y-axis title and x-axis title leave blank
  labs(y="Soil SOC (mg/g)", x = "")+ 
  # add plot title
  ggtitle("Mean ± SE of Soil SOC")+
  coord_flip()+
  # customize plot themes
  theme(
        axis.line = element_line(colour = "gray"),
        # plot title position at center
        plot.title = element_text(hjust = 0.5),
        # axis title font size
        axis.title.x = element_text(size = 14), 
        # X and  axis font size
        axis.text.y=element_text(size=12,vjust = 0.5, hjust=0.5, colour='black'),
        axis.text.x = element_text(size=12))
```

```{r}
#Task12

T1 <- bd_green_house %>% dplyr::select(SW, GAs)

T2 <- bd_green_house %>% dplyr::select(SW, GAs) 

# Two-Sample T-test
t.test(x=T1$GAs,
       y=T2$GAs, 
       paired = TRUE,
       alternative = "greater")


```

